sudo: False

language: python

matrix:
  include:
    - python: 2.6
    - python: 2.7
      env: SPARK_VERSION=1.2
    - python: 2.7
      env: SPARK_VERSION=1.3
    - python: 3.3
    - python: 3.4

addons:
  postgresql: "9.3"

services:
    - mongodb
    - postgres
    - mysql

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n odo-test python=$TRAVIS_PYTHON_VERSION pytest numpy pandas sqlalchemy h5py pip cython bcolz coverage networkx toolz multipledispatch pytables dynd-python pymongo paramiko boto
  - source activate odo-test

  # datashape
  - conda install datashape -c blaze

  # Install various deps
  - pip install sas7bdat
  - pip install git+git://github.com/blaze/dask.git --upgrade
  - pip install dill --upgrade

  # install pyspark
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then conda install spark=$SPARK_VERSION -c blaze -c https://conda.binstar.org/blaze/channel/dev; fi

  # Install Bokeh
  - if [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; then conda install bokeh psycopg2 pymysql; fi

  # For bcolz
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda install unittest2 && pip install psycopg2 pymysql; fi

  # redshift sqlalchemy dialect
  - pip install --upgrade git+git://github.com/cpcloud/redshift_sqlalchemy

# Before_script section stolen from fabric
# See license https://github.com/fabric/fabric/blob/master/LICENSE
before_script:
 # Allow us to SSH passwordless to localhost
 - ssh-keygen -f ~/.ssh/id_rsa -N ""
 - cp ~/.ssh/{id_rsa.pub,authorized_keys}
 # Creation of an SSH agent for testing forwarding
 - eval $(ssh-agent)
 - ssh-add
 - mysql -e "create database if not exists test;" -u root
 - psql -c "create database test;" -U postgres

script:
    - py.test -v --doctest-modules odo

notifications:
  email: false
