sudo: False

language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"

addons:
  postgresql: "9.3"

services:
    - mongodb
    - postgres
    - mysql

install:
  # Install conda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda

  # Install dependencies
  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION pytest numpy pandas sqlalchemy h5py pip cython bcolz coverage networkx toolz multipledispatch pytables dynd-python
  - source activate test-environment

  # Install PyMongo
  - pip install pymongo pymysql paramiko sas7bdat psycopg2

  # Install DataShape
  - pip install --upgrade git+http://github.com/ContinuumIO/datashape

  # For bcolz
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then conda install unittest2; fi

# Before_script section stolen from fabric
# See license https://github.com/fabric/fabric/blob/master/LICENSE
before_script:
 # Allow us to SSH passwordless to localhost
 - ssh-keygen -f ~/.ssh/id_rsa -N ""
 - cp ~/.ssh/{id_rsa.pub,authorized_keys}
 # Creation of an SSH agent for testing forwarding
 - eval $(ssh-agent)
 - ssh-add

script:
    - py.test --doctest-modules into

after_success:
    - pip install coveralls --use-mirrors ; coveralls

notifications:
  email: false
