package:
  name: odo
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}

source:
  git_url: ../

requirements:
  build:
    - python

  run:
    - python
    - datashape >=0.4.4
    - numpy >=1.7
    - pandas >=0.15.0
    - toolz
    - multipledispatch >=0.4.7
    - networkx

test:
  requires:
    - pytest
    - h5py
    - pytables >=3.0.0
    - sqlalchemy >=0.8.0
    - bcolz
    - pymongo >=2.8
    - dask
    - dynd-python
    - paramiko
    - sqlite3 # [win]
    - boto # [not win]
    - bokeh # [not py26]
    - pytables >=3.0.0
    - pip
    - pymysql # [not py26]
    - psycopg2 # [unix and not py26]

  commands:
    - pip install sas7bdat && py.test -vx --pyargs odo -rsxX

about:
  home: https://github.com/ContinuumIO/odo/
  license: BSD
  summary: Data migration
