package:
  name: into
  version: !!str 0.1.3

requirements:
  build:
    - python
    - setuptools
    - datashape
    - numpy
    - pandas
    - toolz
    - multipledispatch
    - networkx

  run:
    - python
    - datashape
    - numpy
    - pandas
    - toolz
    - multipledispatch
    - networkx

test:
  requires:
    - pytest
    - coverage
    - h5py
    - pytables
    - sqlalchemy
    - bcolz

  commands:
    - python -c "import into; into.test(exit=True)"

about:
  home: http://github.com/ContinuumIO/into/
  license: BSD
  summary: 'Data migration utilities'
