package:
  name: odo
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install

source:
  git_url: ../

requirements:
  build:
    - python
    - setuptools
    - datashape
    - numpy
    - pandas
    - toolz
    - multipledispatch
    - networkx

  run:
    - python
    - datashape
    - numpy
    - pandas
    - toolz
    - multipledispatch
    - networkx

test:
  requires:
    - pytest
    - coverage
    - h5py
    - pytables
    - sqlalchemy
    - bcolz
    - pymongo

  commands:
    - python -c "import odo; odo.test(exit=True)"

about:
  home: http://github.com/ContinuumIO/odo/
  license: BSD
  summary: 'Data migration'
